// temp key, will expire after presentation
const TOKEN =
  "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJqdGkiOiI5MGU2OGI1MC04NTY5LTAxMzgtZGUzNC03ZjgyNWM4ZjQ1MTIiLCJpc3MiOiJnYW1lbG9ja2VyIiwiaWF0IjoxNTkwOTI4NzE0LCJwdWIiOiJibHVlaG9sZSIsInRpdGxlIjoicHViZyIsImFwcCI6ImNsYXNzLXByb2plY3QtIn0.ibYDuPGdZ-D45h5RnBJXujfhYkaps_VP7MBnzXmumh8";

export default TOKEN;
